[env]
EPICS_BASE = "/usr/local/epics/base"
EPICS_HOST_ARCH="linux-x86_64"
# EPICS_BASE = "/Users/giilkwon/WorkSpace/EPICS/base-7.0.5"
# EPICS_HOST_ARCH="darwin-x86"
#export EPICS_CA_ADDR_LIST="cag.kstar.kfe.re.kr 127.0.0.1"

# EPICS_CA_ADDR_LIST="127.0.0.1"

EPICS_CA_ADDR_LIST="192.168.1.116"
# EPICS_CA_ADDR_LIST="192.168.219.13"
EPICS_CA_AUTO_ADDR_LIST="no"